export const tabs = ['recommended', 'latest', 'my']
export const professionals = [
  'Java backend',
  'Go',
  'python',
  'C++',
  'database',
  'web front end',
  'Big Data',
  'algorithm engineer',
  'data analysis',
  'Technical Operations',
  'Test Development',
  'UI design',
  'cyber security',
  'Operation and maintenance',
  'Materials Engineering',
  'Embedded Development',
  'mobile communications',
  'Blockchain',
  'civil engineer',
  'Chip R&D',
  'Software development',
  'civil servant'
]